<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sif</string>
	</array>
	<key>name</key>
	<string>Sif</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|else|then|repeat|until|while|end|function|exit|return|next|set|to)\b</string>
			<key>name</key>
			<string>keyword.control.sif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(is|not|and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.sif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((read\s+(a\s+)?line)|(print\s+error)|(write\s+error))\b</string>
			<key>name</key>
			<string>keyword.other.sif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print|write)\b</string>
			<key>name</key>
			<string>keyword.other.sif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-)?[0-9.]+\b</string>
			<key>name</key>
			<string>constant.numeric.sif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|empty|it)\b</string>
			<key>name</key>
			<string>constant.language.sif</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-dash.sif</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.pound.sif</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.sif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.sif</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.sif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.sif</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sif</string>
	<key>uuid</key>
	<string>1A6B5105-AD0B-45C9-A22C-9660DB1D8D16</string>
</dict>
</plist>
