<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>chatter</string>
	</array>
	<key>name</key>
	<string>Chatter</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|else|then|repeat|end|function|exit|return|next|set|to)\b</string>
			<key>name</key>
			<string>keyword.control.chatter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(is|not|and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.chatter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(write[ \t]+line)\b</string>
			<key>name</key>
			<string>keyword.other.chatter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(write)\b</string>
			<key>name</key>
			<string>keyword.other.chatter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-)?[0-9.]+\b</string>
			<key>name</key>
			<string>constant.numeric.chatter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|empty)\b</string>
			<key>name</key>
			<string>constant.language.chatter</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-dash.chatter</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.chatter</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.chatter</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.chatter</string>
	<key>uuid</key>
	<string>1A6B5105-AD0B-45C9-A22C-9660DB1D8D16</string>
</dict>
</plist>
